## 目录以及连接配置
# 连接地址
connect.url: qemu:///system
# 存储卷目录
storage.dir.path: /var/lib/libvirt/images/
# 虚拟机描述
vm.xml.dir.path: /etc/libvirt/qemu/
# iso位置
iso.dir.path: /usr/module/kvm/img/
# noVnc启动websockify.py路径
novnc.dir.path: /usr/module/noVNC-1.1.0/

# 邮箱发送地址
mail.fromMail.addr: nyistxiaozheng@163.com


spring:
## 邮箱配置
  mail:
    host: smtp.163.com
    username: nyistxiaozheng@163.com
    password: password
    default-encoding: UTF-8
## 数据库设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.237.135:3306/libvirt?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      #第一次启动用create, 以后用 update 或 不设置
      ddl-auto: update
                # create 启动时删数据库中的表，然后创建，退出时不删除数据表
                # create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
                # update 如果启动时表格式不一致则更新表，原有数据保留
                # validate 项目启动表结构进行校验 如果不一致则报错
## 前端模板配置
  thymeleaf:
    cache: false


#logging:
#  pattern:
#    console: "%green([%-5p]) %boldYellow([%45logger]) - %magenta(%m) %n"
#  level:
#    实体: TRACE


